unique_ids:
  assets:
    theme.css: CT6PGIKTW45PMH4DZ2MNI7LN7QSWDT2Z
  forms:
    Form1: L2ZOI7IGAH6U4IAWYPBAXON4S7NXGC6W
    Layouts.BaseLayout: KCV5S5S3H3QSFSCUY4FGPBHT4H2P727K
  modules:
    Layouts: 7DRTOVFZMG7MM7KODU3HWKARHAXNKLV5
  scripts: {}
  server_modules: {}
